include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/admin/**
    - lib/auth/**
    - lib/backend/**
    - lib/components/**
    - lib/flutter_flow/**
    - lib/user/**
    - lib/index.dart
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    unnecessary_string_escapes: false
    use_build_context_synchronously: false
    avoid_types_as_parameter_names: false
