include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/admin/**
    - lib/auth/**
    - lib/backend/**
    - lib/components/**
    - lib/flutter_flow/**
    - lib/user/**
    - lib/index.dart

linter:
  rules:
    unnecessary_string_escapes: false
