import '../core/app_role.dart';
import 'models.dart';

final demoCategories = <CategoryModel>[
  const CategoryModel(id: 'accesorios', name: 'Accesorios', description: 'Periféricos y complementos tech.', active: true),
  const CategoryModel(id: 'audio', name: 'Audio', description: 'Audífonos, parlantes y micrófonos.', active: true),
  const CategoryModel(id: 'wearables', name: 'Wearables', description: 'Relojes inteligentes y dispositivos portables.', active: true),
  const CategoryModel(id: 'lifestyle', name: 'Lifestyle', description: 'Productos urbanos para estudio y trabajo.', active: true),
];

final demoProducts = <Product>[
  const Product(
    id: 'keyboard-pro',
    name: 'Keyboard Pro X',
    description: 'Teclado mecánico compacto con switches táctiles y RGB sobrio.',
    category: 'Accesorios',
    price: 249.90,
    stock: 18,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80',
    rating: 4.8,
    isFeatured: true,
    discountRate: .10,
  ),
  const Product(
    id: 'headset-air',
    name: 'Headset Air Studio',
    description: 'Audífonos inalámbricos con cancelación de ruido para estudio y gaming.',
    category: 'Audio',
    price: 319.00,
    stock: 12,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
    rating: 4.7,
    isFeatured: true,
    discountRate: .05,
  ),
  const Product(
    id: 'smartwatch-fit',
    name: 'Smartwatch Fit 2',
    description: 'Reloj inteligente para entrenamiento, sueño y productividad diaria.',
    category: 'Wearables',
    price: 399.90,
    stock: 3,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80',
    rating: 4.6,
    isFeatured: false,
    discountRate: .12,
  ),
  const Product(
    id: 'backpack-tech',
    name: 'Backpack Tech Shield',
    description: 'Mochila urbana resistente al agua con compartimento para laptop.',
    category: 'Lifestyle',
    price: 189.50,
    stock: 21,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',
    rating: 4.5,
    isFeatured: false,
  ),
  const Product(
    id: 'mouse-precision',
    name: 'Mouse Precision 8K',
    description: 'Mouse ergonómico de alta precisión para trabajo, diseño y videojuegos.',
    category: 'Accesorios',
    price: 159.90,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=80',
    rating: 4.9,
    isFeatured: true,
  ),
];

final demoUsers = <AppUser>[
  AppUser(
    id: 'demo-customer',
    email: 'cliente@demo.com',
    fullName: 'Cliente Demo',
    role: AppRole.customer,
    phone: '+51 999 000 001',
    address: 'Arequipa, Perú',
    photoUrl: '',
    paymentMethods: const [
      PaymentMethodProfile(id: 'pm-demo', type: 'Tarjeta simulada', holder: 'Cliente Demo', last4: '4242', isDefault: true),
    ],
    notifications: NotificationPreferences.defaults(),
    createdAt: DateTime(2026),
    demo: true,
  ),
  AppUser(
    id: 'demo-seller',
    email: 'vendedor@demo.com',
    fullName: 'Vendedor Demo',
    role: AppRole.seller,
    phone: '+51 999 000 002',
    address: 'Arequipa, Perú',
    photoUrl: '',
    paymentMethods: const [],
    notifications: NotificationPreferences.defaults(),
    createdAt: DateTime(2026),
    demo: true,
  ),
  AppUser(
    id: 'demo-admin',
    email: 'admin@demo.com',
    fullName: 'Administrador Demo',
    role: AppRole.admin,
    phone: '+51 999 000 003',
    address: 'Arequipa, Perú',
    photoUrl: '',
    paymentMethods: const [],
    notifications: NotificationPreferences.defaults(),
    createdAt: DateTime(2026),
    demo: true,
  ),
];
